const USERS = [
  {
    name: "Amit Sharma",
    age: 28,
    city: "Delhi",
    image: "https://i.pravatar.cc/150?img=1",
  },
  {
    name: "Aman Sharma",
    age: 32,
    city: "Mumbai",
    image: "https://i.pravatar.cc/150?img=2",
  },
  {
    name: "Amir Khan",
    age: 25,
    city: "Bengaluru",
    image: "https://i.pravatar.cc/150?img=3",
  },
  {
    name: "Riya Mehta",
    age: 27,
    city: "Hyderabad",
    image: "https://i.pravatar.cc/150?img=4",
  },
  {
    name: "Neha Verma",
    age: 35,
    city: "Chennai",
    image: "https://i.pravatar.cc/150?img=5",
  },
  {
    name: "Raj Patel",
    age: 22,
    city: "Ahmedabad",
    image: "https://i.pravatar.cc/150?img=6",
  },
  {
    name: "Simran Kaur",
    age: 30,
    city: "Pune",
    image: "https://i.pravatar.cc/150?img=7",
  },
  {
    name: "Amitabh Joshi",
    age: 29,
    city: "Kolkata",
    image: "https://i.pravatar.cc/150?img=8",
  },
  {
    name: "Priya Singh",
    age: 31,
    city: "Jaipur",
    image: "https://i.pravatar.cc/150?img=9",
  },
  {
    name: "Amanpreet Singh",
    age: 26,
    city: "Surat",
    image: "https://i.pravatar.cc/150?img=10",
  },
  {
    name: "Sneha Reddy",
    age: 28,
    city: "Visakhapatnam",
    image: "https://i.pravatar.cc/150?img=11",
  },
  {
    name: "Vikram Rao",
    age: 34,
    city: "Lucknow",
    image: "https://i.pravatar.cc/150?img=12",
  },
  {
    name: "Tanvi Sharma",
    age: 24,
    city: "Nagpur",
    image: "https://i.pravatar.cc/150?img=13",
  },
  {
    name: "Arjun Mehra",
    age: 29,
    city: "Indore",
    image: "https://i.pravatar.cc/150?img=14",
  },
  {
    name: "Ananya Gupta",
    age: 27,
    city: "Bhopal",
    image: "https://i.pravatar.cc/150?img=15",
  },
  {
    name: "Deepak Kumar",
    age: 33,
    city: "Patna",
    image: "https://i.pravatar.cc/150?img=16",
  },
  {
    name: "Karan Malhotra",
    age: 26,
    city: "Ludhiana",
    image: "https://i.pravatar.cc/150?img=17",
  },
  {
    name: "Swati Desai",
    age: 25,
    city: "Agra",
    image: "https://i.pravatar.cc/150?img=18",
  },
  {
    name: "Farhan Sheikh",
    age: 29,
    city: "Nashik",
    image: "https://i.pravatar.cc/150?img=19",
  },
  {
    name: "Ankit Sharma",
    age: 31,
    city: "Kanpur",
    image: "https://i.pravatar.cc/150?img=20",
  },
  {
    name: "Meera Nair",
    age: 30,
    city: "Kochi",
    image: "https://i.pravatar.cc/150?img=21",
  },
  {
    name: "Aishwarya Rao",
    age: 28,
    city: "Thane",
    image: "https://i.pravatar.cc/150?img=22",
  },
  {
    name: "Ravi Verma",
    age: 35,
    city: "Meerut",
    image: "https://i.pravatar.cc/150?img=23",
  },
  {
    name: "Ishaan Sharma",
    age: 33,
    city: "Gwalior",
    image: "https://i.pravatar.cc/150?img=24",
  },
  {
    name: "Pooja Bhatt",
    age: 26,
    city: "Vijayawada",
    image: "https://i.pravatar.cc/150?img=25",
  },
  {
    name: "Aman Kapoor",
    age: 26,
    city: "Rajkot",
    image: "https://i.pravatar.cc/150?img=26",
  },
  {
    name: "Armaan Jain",
    age: 32,
    city: "Amritsar",
    image: "https://i.pravatar.cc/150?img=27",
  },
  {
    name: "Sanya Malhotra",
    age: 27,
    city: "Varanasi",
    image: "https://i.pravatar.cc/150?img=28",
  },
  {
    name: "Ankita Shah",
    age: 30,
    city: "Ranchi",
    image: "https://i.pravatar.cc/150?img=29",
  },
  {
    name: "Alok Yadav",
    age: 34,
    city: "Jodhpur",
    image: "https://i.pravatar.cc/150?img=30",
  },
];

export { USERS };
